In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original 1D Array:")
print(arr)

Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
arr_reshaped = arr.reshape(2, 5)
print("Reshaped to 2x5:")
print(arr_reshaped)

Reshaped to 2x5:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
matrix = np.matrix(arr_reshaped)
print("Matrix:")
print(matrix)

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
print("Transpose of matrix:")
print(matrix.T)

# Matrix multiplication (with its transpose)
print("Matrix * Transpose:")
print(matrix @ matrix.T)

Transpose of matrix:
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
Matrix * Transpose:
[[ 55 130]
 [130 330]]


In [6]:
arr = np.array([10, 25, 30, 5, 60])
print("Original Array:")
print(arr)

Original Array:
[10 25 30  5 60]


In [7]:
greater_than_20 = arr > 20
print("Greater than 20 (Boolean Mask):")
print(greater_than_20)

print("Elements Greater Than 20:")
print(arr[greater_than_20])

Greater than 20 (Boolean Mask):
[False  True  True False  True]
Elements Greater Than 20:
[25 30 60]


In [8]:
less_equal_10 = arr <= 10
print("Less than or equal to 10 (Boolean Mask):")
print(less_equal_10)

print("Elements <= 10:")
print(arr[less_equal_10])

Less than or equal to 10 (Boolean Mask):
[ True False False  True False]
Elements <= 10:
[10  5]


In [9]:
arr2 = np.array([15, 20, 35, 2, 60])
print("Second Array:")
print(arr2)

print("arr > arr2:")
print(arr > arr2)

print("Elements in arr greater than arr2:")
print(arr[arr > arr2])

Second Array:
[15 20 35  2 60]
arr > arr2:
[False  True False  True False]
Elements in arr greater than arr2:
[25  5]
